### ISSUE TITLE
Return back the UINavigationController delegate to parent coordinator when share the UINavigationController

### ISSUE THREAD

**Issue by calvingit** [radianttap/Coordinator#12]
If parent and children share the same UINavigationController, children should return back the delegate of UINavigationController to parent after stopped.

I think the `open override func stop(with completion: @escaping () -> Void) ` method of `NavigationCoordinator` should like this:

```swift
open override func stop(with completion: @escaping () -> Void) {
     if let parent = self.parent as? NavigationCoordinator,
         parent.rootViewController == rootViewController 
     {
         rootViewController.delegate = parent
     }
     else
     {
         rootViewController.delegate = nil
     }

	for vc in viewControllers {
		guard let index = rootViewController.viewControllers.index(of: vc) else { continue }
		rootViewController.viewControllers.remove(at: index)
	}

	viewControllers.removeAll()

	super.stop(with: completion)
}
```

Is it right?

**Comment by MarcSteven** [comment]
Compared with the code ,add the judgement logic here .I think it's a great design to reduce the bugs.We should know when we must relinquish the delegate completely ,so that's the difference between the code. @radianttap Thank for your sharing and contribution ....


```
open override func stop(with completion: @escaping () -> Void) {
			rootViewController.delegate = nil

			for vc in viewControllers {
			guard let index = rootViewController.viewControllers.index(of: vc) else { continue }
			rootViewController.viewControllers.remove(at: index)
		}
		viewControllers.removeAll()
		super.stop(with: completion)
	} 
```

**Comment by radianttap** [comment]
It's not that simple, sadly.

If parentCoordinator has, say 2 child Coordinators, and second one is popped, maybe the 1st child should take ownership, not the parent. And maybe not, it really depends on the app. 
(Only if no child Coordinators are left then parent Coordinator should take ownership.)
This is related to #10 and same as there – I don't see a straight-forward solution that works in all cases.

Coordinator is deliberatelly made simple to cover just the basics. Dealing with logic like this is something that app should decide in its own subclass of NavigationCoordinator – only in the context of the specific app a decision can be made what should happen is particular Coordinator instance is stopped. 

Example for the shop app I used as demo: say 

- You are on CatalogCoordinator and want to buy something 
- You tap on Buy now
- This is routed up to the CatalogCoordinator which then checks with AccountManager are you logged in
- If not, it pushes AccountCoordinator to show LoginVC
- When login is done, it _could_ return you to CatalogCoordinator and you tap Buy now again but...
- it's better if it would just continue the flow and push PaymentCoordinator

That's why I don't think this is something that library should decide on its own – it's app developer's job.
