### ISSUE TITLE
Crash on Accessing Parent Coordinator

### ISSUE THREAD

**Issue by nischu** [radianttap/Coordinator#32]
I experienced crashes from time to time when accessing a UIViewController's parentCoordinator property.

As it turns out, the parentCoordinator is realized as an Objective-C Associated Object using the OBJC_ASSOCIATION_ASSIGN association policy, which, in newer Objective-C parlance, means unsafe-unretained.

While I agree that the parent coordinator's lifetime  _should_ always exceed the child coordinator's lifetime, there is no way to enforce that. Any object may establish a strong reference to the child coordinator (for instance, by submitting an asynchronous operation) that may keep the child coordinator alive although the parent was instructed to stopChild.

This finally leads to a crash for the next caller that accesses the parentCoordinator property, as the AssociatedKeys.ParentCoordinator contains a stale pointer once the parent coordinator goes away.

I would propose to establish a real weak association where, in this use-case, the parentCoordinator becomes nil. Unfortunately, there is a little quirk required because the only safe association policy is OBJC_ASSOCIATION_RETAIN, requiring a trampoline object that establishes the actual weak reference.

The only equally safe alternative I see would be to make the parentCoordinator a strong reference, but that would lead to retain cycles for obvious reasons.

What are your thoughts?

I am linking a pull request as my proposed solution, open for discussion.

Kind regards
Nico

**Comment by nischu** [comment]
Pardon me, I do not know how to link my pull request to this issue:
https://github.com/radianttap/Coordinator/pull/33

**Comment by radianttap** [comment]
Ah, I first read the PR and commented there :)

I would love to make this better if possible, but not for the price of possible memory leak.

I am really wary of memory leaks, of coordinators staying in memory when I don't intend them to. It usually means all their `viewControllers` also stay in memory since they are strongly ref-ed by their Coordinator. I honestly prefer to just let it crash and force me to fix my logic to either `nil` or re-assign `parentCoordinator` properly.

As per one of my favourite sayings: "broken gets fixed, shady lasts forever"

**Comment by radianttap** [comment]
merged the PR
