### ISSUE TITLE
Track Dismissal of RootViewController

### ISSUE THREAD

**Issue by fabb** [radianttap/Coordinator#6]
Quite a few of Coordinator libraries have a problem keeping the Coordinator hierarchy in sync with the ViewController hierarchy (e.g. [these ones](https://github.com/michalciurus/KatanaRouter/issues/6)). How do you think we should prevent that a Coordinator's `rootViewController` gets dismissed by some `dismiss` call or similar without the Coordinator noticing it?

**Comment by radianttap** [comment]
Interesting, haven't though of that. I would say use common sense :) if not for a fact that I spent considerable time in active project making sure that all my popups are dismissed through coordinatingResponder methods. I mention popups because they are the problem.

For regular UINavigationController hierarchy, I have already [solved it](https://github.com/radianttap/Coordinator/blob/master/NavigationCoordinator.swift#L32). Works great in practice.

**Comment by fabb** [comment]
Yeah, I went through similar cleanup stuffs (a very mean thing was that when clicking the currently active tabbar item of a tabbar controller, it would pop back a contained navigation controller as well). Unfortunately it's not always possible to avoid such direct calls to `dismiss` if using libraries that one cannot easily change. I haven't found a way to solve this, but the base of the problem is probably this: https://stackoverflow.com/questions/47350720/how-can-a-presentingviewcontroller-get-notified-that-its-presentedviewcontroller

**Comment by radianttap** [comment]
Without some cooperation from UIKit (which is unlikely), I don't think this can be resolved in a satisfactory way. All that we are left with is common sense and proper testing of UI scenarios.

In my apps using Coordinator, I make sure to wrap all the modals inside `PopupCoordinator`, which has one coordinatingResponder message called `popupDismiss` which properly handles dismissals. Direct usage of UIViewController.dismiss() is no-no. And it rather works, so far.
